"""
定时报告生成模块
提供定时任务调度功能，用于自动生成周期性分析报告
"""

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
import logging
from datetime import datetime, timedelta, date
from typing import Dict, List, Optional, Any
from sqlalchemy.orm import Session
from sqlalchemy import text

import config
from app.database import SessionLocal, get_db_context
from app.models import User, Dataset, ProductData
from app.services.email_service import email_service

logger = logging.getLogger(__name__)

# 创建调度器实例
scheduler = BackgroundScheduler()


# ==================== 多语言邮件模板 ====================

REPORT_TEMPLATES = {
    'zh': {
        'daily_subject': '📊 {app_name} - 每日营销报告 {date}',
        'daily_title': '每日营销数据报告',
        'weekly_subject': '📊 {app_name} - 每周营销报告 {date}',
        'weekly_title': '每周营销数据报告',
        'summary': '数据概览',
        'total_products': '产品总数',
        'visible_products': '可见产品',
        'hidden_products': '隐藏产品',
        'total_sales': '总销量',
        'total_profit': '总利润',
        'direct_sales': '直接销量',
        'indirect_sales': '间接销量',
        'promoted_sales': '推广销量',
        'vs_yesterday': 'vs 昨日',
        'vs_last_week': 'vs 上周',
        'top_products': '🏆 Top {n} 热销产品',
        'top_products_weekly': '🏆 Top {n} 产品（本周）',
        'product_id': '产品ID',
        'product_name': '产品名称',
        'sales': '销量',
        'profit': '利润',
        'profit_margin': '利润率',
        'anomaly_title': '⚠️ 异常检测提醒',
        'anomaly_count': '共发现 {count} 个异常',
        'anomaly_type': '异常类型',
        'z_score': 'Z-score',
        'low_sales': '销量异常低',
        'high_sales': '销量异常高',
        'ai_insight': '💡 AI 洞察摘要',
        'week_overview': '本周概览',
        'best_day': '最佳表现日',
        'trend': '趋势分析',
        'recommendation': '优化建议',
        'footer': '此报告由 {app_name} 自动生成',
        'footer_unsubscribe': '退订报告',
        'no_data': '暂无数据',
        'no_subscription': '您尚未订阅任何报告',
        'change_preference': '更改订阅设置',
        'greeting': '您好，{username}！',
        'report_intro': '以下是您的 {period} 数据分析报告：',
        'change_up': '↑ {pct}%',
        'change_down': '↓ {pct}%',
        'no_change': '持平',
    },
    'en': {
        'daily_subject': '📊 {app_name} - Daily Marketing Report {date}',
        'daily_title': 'Daily Marketing Report',
        'weekly_subject': '📊 {app_name} - Weekly Marketing Report {date}',
        'weekly_title': 'Weekly Marketing Report',
        'summary': 'Overview',
        'total_products': 'Total Products',
        'visible_products': 'Visible',
        'hidden_products': 'Hidden',
        'total_sales': 'Total Sales',
        'total_profit': 'Total Profit',
        'direct_sales': 'Direct Sales',
        'indirect_sales': 'Indirect Sales',
        'promoted_sales': 'Promoted Sales',
        'vs_yesterday': 'vs Yesterday',
        'vs_last_week': 'vs Last Week',
        'top_products': '🏆 Top {n} Products',
        'top_products_weekly': '🏆 Top {n} Products (This Week)',
        'product_id': 'Product ID',
        'product_name': 'Product Name',
        'sales': 'Sales',
        'profit': 'Profit',
        'profit_margin': 'Margin',
        'anomaly_title': '⚠️ Anomaly Alerts',
        'anomaly_count': '{count} anomalies detected',
        'anomaly_type': 'Type',
        'z_score': 'Z-score',
        'low_sales': 'Abnormally Low Sales',
        'high_sales': 'Abnormally High Sales',
        'ai_insight': '💡 AI Insights',
        'week_overview': 'Week Overview',
        'best_day': 'Best Performance',
        'trend': 'Trend Analysis',
        'recommendation': 'Recommendations',
        'footer': 'Auto-generated by {app_name}',
        'footer_unsubscribe': 'Unsubscribe',
        'no_data': 'No data available',
        'no_subscription': 'You have no active report subscriptions',
        'change_preference': 'Change subscription settings',
        'greeting': 'Hello, {username}!',
        'report_intro': 'Here is your {period} data analysis report:',
        'change_up': '↑ {pct}%',
        'change_down': '↓ {pct}%',
        'no_change': 'No change',
    },
    'fr': {
        'daily_subject': '📊 {app_name} - Rapport Marketing Quotidien {date}',
        'daily_title': 'Rapport Marketing Quotidien',
        'weekly_subject': '📊 {app_name} - Rapport Marketing Hebdomadaire {date}',
        'weekly_title': 'Rapport Marketing Hebdomadaire',
        'summary': 'Aperçu',
        'total_products': 'Total Produits',
        'visible_products': 'Visibles',
        'hidden_products': 'Cachés',
        'total_sales': 'Ventes Totales',
        'total_profit': 'Profit Total',
        'direct_sales': 'Ventes Directes',
        'indirect_sales': 'Ventes Indirectes',
        'promoted_sales': 'Ventes Promues',
        'vs_yesterday': 'vs Hier',
        'vs_last_week': 'vs Semaine Précédente',
        'top_products': '🏆 Top {n} Produits',
        'top_products_weekly': '🏆 Top {n} Produits (Cette Semaine)',
        'product_id': 'ID Produit',
        'product_name': 'Nom du Produit',
        'sales': 'Ventes',
        'profit': 'Profit',
        'profit_margin': 'Marge',
        'anomaly_title': '⚠️ Alertes d\'Anomalies',
        'anomaly_count': '{count} anomalies détectées',
        'anomaly_type': 'Type',
        'z_score': 'Z-score',
        'low_sales': 'Ventes Abnormallyment Basses',
        'high_sales': 'Ventes Abnormallyment Élevées',
        'ai_insight': '💡 Perspectives IA',
        'week_overview': 'Aperçu de la Semaine',
        'best_day': 'Meilleure Performance',
        'trend': 'Analyse de Tendance',
        'recommendation': 'Recommandations',
        'footer': 'Généré automatiquement par {app_name}',
        'footer_unsubscribe': 'Se désabonner',
        'no_data': 'Aucune donnée disponible',
        'no_subscription': 'Vous n\'avez aucun abonnement actif',
        'change_preference': 'Modifier les paramètres',
        'greeting': 'Bonjour, {username}!',
        'report_intro': 'Voici votre rapport d\'analyse {period} :',
        'change_up': '↑ {pct}%',
        'change_down': '↓ {pct}%',
        'no_change': 'Stable',
    }
}


def _get_user_language(user: User) -> str:
    """从用户信息推断语言偏好，默认为英语"""
    # 简单策略：检查邮箱域名
    email = (user.email or '').lower()
    if email.endswith(('.cn', '.com.cn')):
        return 'zh'
    # 可扩展：从用户设置中读取语言偏好
    return 'en'


def _t(lang: str, key: str, **kwargs) -> str:
    """获取翻译文本"""
    template = REPORT_TEMPLATES.get(lang, REPORT_TEMPLATES['en']).get(key, key)
    return template.format(**kwargs)


def _format_number(n: float) -> str:
    """格式化数字"""
    if isinstance(n, float):
        if abs(n) >= 1000:
            return f"{n:,.1f}"
        return f"{n:.2f}"
    return f"{n:,}"


def _format_profit(p: float) -> str:
    """格式化利润（支持Credits和USD）"""
    credits = f"{p:,.2f} Credits"
    usd = p * 0.0004
    return f"{credits} (${usd:.2f})"


def _calc_change_pct(current: float, previous: float) -> str:
    """计算变化百分比"""
    if previous == 0:
        return '—'
    change = ((current - previous) / abs(previous)) * 100
    if change > 0:
        return f"↑ {change:.1f}%"
    elif change < 0:
        return f"↓ {abs(change):.1f}%"
    return '0%'


def _get_products_for_user(user_id: int) -> List[Dict[str, Any]]:
    """获取用户最新的产品数据"""
    with get_db_context() as db:
        dataset = db.query(Dataset).filter(
            Dataset.user_id == user_id
        ).order_by(Dataset.upload_time.desc()).first()
        
        if not dataset:
            return []
        
        products = db.query(ProductData).filter(
            ProductData.dataset_id == dataset.id
        ).all()
        
        return [
            {
                'product_id': p.product_id,
                'product_name': p.product_name,
                'price': float(p.price or 0),
                'profit': float(p.profit or 0),
                'visible': p.visible,
                'direct_sales': float(p.direct_sales or 0),
                'indirect_sales': float(p.indirect_sales or 0),
                'promoted_sales': float(p.promoted_sales or 0),
                'cart_adds': float(p.cart_adds or 0),
                'wishlist_adds': float(p.wishlist_adds or 0),
                'organic_impressions': float(p.organic_impressions or 0),
                'paid_impressions': float(p.paid_impressions or 0),
            }
            for p in products
        ]


def _analyze_with_analytics(products: List[Dict]) -> Dict:
    """使用 AnalyticsService 进行数据分析"""
    from app.services.analytics import AnalyticsService
    
    if not products:
        return {
            'summary': {},
            'top_products': [],
            'bottom_products': [],
            'anomalies': [],
            'visibility': {},
            'traffic': {},
        }
    
    analytics = AnalyticsService(products)
    
    summary = analytics.get_summary_metrics()
    top_products = analytics.get_top_products(limit=10, metric='profit')
    bottom_products = analytics.get_bottom_products(limit=5, metric='profit')
    anomalies = analytics.detect_sales_anomalies(threshold=2.0)
    visibility = analytics.get_visibility_analysis()
    
    # 计算各产品总销量
    for p in top_products:
        p['total_sales'] = (
            (p.get('direct_sales') or 0) +
            (p.get('indirect_sales') or 0) +
            (p.get('promoted_sales') or 0)
        )
    
    for p in bottom_products:
        p['total_sales'] = (
            (p.get('direct_sales') or 0) +
            (p.get('indirect_sales') or 0) +
            (p.get('promoted_sales') or 0)
        )
    
    return {
        'summary': summary,
        'top_products': top_products,
        'bottom_products': bottom_products,
        'anomalies': anomalies,
        'visibility': visibility,
        'traffic': analytics.get_traffic_analysis(),
    }


def _generate_ai_insight(analysis: Dict, lang: str = 'en') -> str:
    """基于分析数据生成AI洞察"""
    summary = analysis.get('summary', {})
    top_products = analysis.get('top_products', [])
    anomalies = analysis.get('anomalies', [])
    
    insights = []
    t = lambda k, **kw: _t(lang, k, **kw)
    
    # 基于销量的洞察
    total_sales = summary.get('total_sales', 0)
    if total_sales == 0:
        insights.append(t('no_data'))
        return insights[0]
    
    # Top产品洞察
    if top_products:
        best = top_products[0]
        best_name = (best.get('product_name') or best.get('product_id', 'N/A'))[:30]
        best_sales = best.get('total_sales', 0)
        if best_sales > 0:
            insights.append(f"🏆 **{best_name}** — {t('sales')}: {int(best_sales)}")
    
    # 异常检测洞察
    if anomalies:
        low_count = sum(1 for a in anomalies if a.get('z_score', 0) < 0)
        high_count = len(anomalies) - low_count
        if low_count > 0:
            insights.append(f"⚠️ {low_count} {t('low_sales')} {t('product_id')}")
        if high_count > 0:
            insights.append(f"🚀 {high_count} {t('high_sales')}")
    
    # 可见性洞察
    visibility = analysis.get('visibility', {})
    if visibility:
        visible_pct = 0
        total_p = visibility.get('visible', {}).get('count', 0) + visibility.get('hidden', {}).get('count', 0)
        if total_p > 0:
            visible_pct = visibility.get('visible', {}).get('count', 0) / total_p * 100
            if visible_pct < 30:
                insights.append(f"💡 {int(visible_pct)}% products visible — consider increasing visibility for hidden items")
    
    # 利润率洞察
    if top_products:
        high_margin = [p for p in top_products if p.get('profit', 0) > 100]
        if len(high_margin) >= 3:
            insights.append(f"💡 {len(high_margin)}+ high-margin products detected — great pricing strategy!")
    
    return '\n'.join(insights) if insights else t('no_data')


def _build_report_html(
    analysis: Dict,
    tpl: Dict,
    period: str,
    date_str: str,
    username: str,
    top_limit: int = 5
) -> str:
    """构建报告HTML内容"""
    summary = analysis.get('summary', {})
    
    # 计算总销量
    def total_sales(p):
        return int((p.get('direct_sales') or 0) + (p.get('indirect_sales') or 0) + (p.get('promoted_sales') or 0))
    
    top_products = analysis.get('top_products', [])[:top_limit]
    anomalies = analysis.get('anomalies', [])[:5]
    
    # 异常HTML
    anomaly_html = ''
    if anomalies:
        anomaly_items = []
        for a in anomalies:
            product_id = a.get('product_id', 'N/A')
            product_name = (a.get('product_name') or 'N/A')[:30]
            z = abs(a.get('z_score') or 0)
            a_type = tpl.get('low_sales') if a.get('z_score', 0) < 0 else tpl.get('high_sales')
            anomaly_items.append(
                f'<div style="background:#fff3cd;padding:10px;border-radius:5px;margin:5px 0;font-size:13px;">'
                f'<strong>{product_id}</strong> — {product_name}<br>'
                f'<small style="color:#856404">{a_type} (Z: {z:.2f})</small></div>'
            )
        anomaly_html = f'''
        <div style="margin:20px 0;">
            <h2 style="color:#856404;font-size:18px;margin-bottom:10px;">{tpl.get('anomaly_title')}</h2>
            {"".join(anomaly_items)}
        </div>'''
    
    # Top产品行
    def product_row(p, idx):
        name = (p.get('product_name') or p.get('product_id', 'N/A'))[:35]
        sales = total_sales(p)
        profit = p.get('profit', 0)
        margin = (profit / p.get('price', 1) * 100) if p.get('price', 0) > 0 else 0
        return f'''
        <tr style="{'background:#f0f7ff' if idx % 2 == 0 else 'white'}">
            <td style="padding:10px;border-bottom:1px solid #eee;font-size:13px;">{p.get('product_id','')}</td>
            <td style="padding:10px;border-bottom:1px solid #eee;font-size:13px;">{name}</td>
            <td style="padding:10px;border-bottom:1px solid #eee;text-align:center;font-size:13px;">{int(sales)}</td>
            <td style="padding:10px;border-bottom:1px solid #eee;text-align:right;font-size:13px;">{profit:.0f} ({margin:.1f}%)</td>
        </tr>'''
    
    top_rows = ''.join(product_row(p, i) for i, p in enumerate(top_products))
    
    # AI洞察
    ai_insight = _generate_ai_insight(analysis, 'en')  # AI洞察固定用英文
    
    unsubscribe_url = f"{config.SITE_URL}/profile"
    
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 1.6; color: #333; background:#f5f7fa; }}
        .container {{ max-width: 700px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px 20px; border-radius: 16px 16px 0 0; text-align: center; }}
        .header h1 {{ margin: 0 0 8px 0; font-size: 24px; }}
        .header p {{ margin: 0; opacity: 0.9; font-size: 14px; }}
        .body {{ background: white; padding: 30px 25px; border-radius: 0 0 16px 16px; }}
        .greeting {{ font-size: 16px; color: #333; margin-bottom: 20px; }}
        .metrics {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin: 20px 0; }}
        .metric-card {{ background: #f8f9fa; border-radius: 10px; padding: 16px; text-align: center; }}
        .metric-value {{ font-size: 22px; font-weight: bold; color: #667eea; }}
        .metric-label {{ font-size: 12px; color: #888; margin-top: 4px; }}
        .metric-card.highlight {{ background: linear-gradient(135deg, #667eea20, #764ba220); border: 1px solid #667eea40; }}
        .section-title {{ font-size: 16px; font-weight: bold; color: #333; margin: 25px 0 12px 0; padding-bottom: 8px; border-bottom: 2px solid #667eea; }}
        table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
        th {{ background: #f0f2f7; color: #555; padding: 10px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }}
        .ai-insight {{ background: linear-gradient(135deg, #667eea10, #764ba210); border: 1px solid #667eea30; border-radius: 10px; padding: 15px; margin: 20px 0; font-size: 14px; line-height: 1.8; }}
        .footer {{ text-align: center; color: #999; font-size: 12px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; }}
        .footer a {{ color: #667eea; text-decoration: none; }}
        .unsub {{ margin-top: 15px; }}
        @media (max-width: 480px) {{
            .metrics {{ grid-template-columns: 1fr 1fr; gap: 8px; }}
            .metric-value {{ font-size: 18px; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 {config.APP_NAME}</h1>
            <p>{tpl.get(period + '_title')} — {date_str}</p>
        </div>
        <div class="body">
            <p class="greeting">{tpl.get('greeting', username=username or 'Creator')}</p>
            <p>{tpl.get('report_intro', period=tpl.get(period + '_title').lower())}</p>
            
            <!-- 指标卡片 -->
            <div class="metrics">
                <div class="metric-card highlight">
                    <div class="metric-value">{_format_number(summary.get('total_products', 0))}</div>
                    <div class="metric-label">{tpl.get('total_products')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{_format_number(summary.get('total_sales', 0))}</div>
                    <div class="metric-label">{tpl.get('total_sales')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{summary.get('total_profit', 0):,.0f}</div>
                    <div class="metric-label">{tpl.get('total_profit')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{_format_number(summary.get('visible_products', 0))}</div>
                    <div class="metric-label">{tpl.get('visible_products')}</div>
                </div>
            </div>
            
            <!-- 销售额细分 -->
            <div class="metrics">
                <div class="metric-card">
                    <div class="metric-value">{_format_number(summary.get('direct_sales', 0))}</div>
                    <div class="metric-label">{tpl.get('direct_sales')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{_format_number(summary.get('indirect_sales', 0))}</div>
                    <div class="metric-label">{tpl.get('indirect_sales')}</div>
                </div>
            </div>
            
            <!-- Top产品 -->
            {f'''
            <div class="section-title">{tpl.get("top_products", n=top_limit)}</div>
            <table>
                <thead><tr><th>{tpl.get('product_id')}</th><th>{tpl.get('product_name')}</th><th style="text-align:center">{tpl.get('sales')}</th><th style="text-align:right">{tpl.get('profit')} ({tpl.get('profit_margin')})</th></tr></thead>
                <tbody>{top_rows}</tbody>
            </table>
            ''' if top_products else f'<p style="color:#999;font-size:14px;">{tpl.get("no_data")}</p>'}
            
            <!-- 异常检测 -->
            {anomaly_html}
            
            <!-- AI洞察 -->
            <div class="section-title">{tpl.get('ai_insight')}</div>
            <div class="ai-insight">
                {ai_insight}
            </div>
            
            <!-- 页脚 -->
            <div class="footer">
                <p>{tpl.get('footer', app_name=config.APP_NAME)}</p>
                <div class="unsub">
                    <a href="{unsubscribe_url}">{tpl.get('change_preference')}</a>
                    &nbsp;|&nbsp;
                    <a href="{unsubscribe_url}">{tpl.get('footer_unsubscribe')}</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
    """
    return html


# ==================== 报告生成核心逻辑 ====================

def _generate_report_for_user(
    user: User,
    products: List[Dict],
    report_type: str  # 'daily' or 'weekly'
) -> bool:
    """
    为单个用户生成并发送报告
    Returns: 是否发送成功
    """
    lang = _get_user_language(user)
    tpl = REPORT_TEMPLATES.get(lang, REPORT_TEMPLATES['en'])
    
    today = date.today()
    date_str = today.strftime('%Y-%m-%d')
    
    if report_type == 'daily':
        subject = tpl.get('daily_subject', app_name=config.APP_NAME, date=date_str)
    else:
        # 每周报告显示本周范围
        week_start = today - timedelta(days=today.weekday())
        week_end = week_start + timedelta(days=6)
        date_str = f"{week_start.strftime('%m/%d')} - {week_end.strftime('%m/%d')}"
        subject = tpl.get('weekly_subject', app_name=config.APP_NAME, date=date_str)
    
    if not products:
        logger.info(f"用户 {user.email} 没有产品数据，跳过{report_type}报告")
        return False
    
    # 分析数据
    analysis = _analyze_with_analytics(products)
    
    # 构建HTML
    top_limit = 5 if report_type == 'daily' else 10
    html_content = _build_report_html(
        analysis=analysis,
        tpl=tpl,
        period=report_type,
        date_str=date_str,
        username=user.username or user.email.split('@')[0],
        top_limit=top_limit
    )
    
    # 发送邮件
    success, msg = email_service.send_report(
        to_emails=[user.email],
        subject=subject,
        html_content=html_content
    )
    
    if success:
        logger.info(f"{report_type.capitalize()}报告已发送给 {user.email}: {msg}")
    else:
        logger.warning(f"{report_type.capitalize()}报告发送失败 {user.email}: {msg}")
    
    return success


def generate_daily_report():
    """
    生成每日报告的定时任务
    为所有订阅每日报告的用户生成并发送报告
    """
    logger.info(f"🕐 定时任务执行: 生成每日报告 - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        with get_db_context() as db:
            # 查找所有订阅每日报告的用户
            users = db.query(User).filter(
                User.report_preference == 'daily',
                User.is_active == True
            ).all()
        
        total = len(users)
        success_count = 0
        fail_count = 0
        
        for user in users:
            try:
                products = _get_products_for_user(user.id)
                if _generate_report_for_user(user, products, 'daily'):
                    success_count += 1
                else:
                    fail_count += 1
            except Exception as user_err:
                logger.error(f"为用户 {user.email} 生成每日报告失败: {user_err}", exc_info=True)
                fail_count += 1
        
        logger.info(f"✅ 每日报告任务完成: 共 {total} 位订阅用户, 成功 {success_count}, 失败 {fail_count}")
        
    except Exception as e:
        logger.error(f"❌ 每日报告任务执行失败: {e}", exc_info=True)
        # 不向上抛出，避免调度器崩溃
        pass


def generate_weekly_report():
    """
    生成每周报告的定时任务
    为所有订阅每周报告的用户生成并发送报告
    """
    logger.info(f"🕐 定时任务执行: 生成每周报告 - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        # 每周报告只在周一发送
        today = date.today()
        if today.weekday() != 0:  # 0 = Monday
            logger.info(f"今天不是周一，跳过每周报告（将在周一执行）")
            return
        
        with get_db_context() as db:
            # 查找所有订阅每周报告的用户（包括默认用户）
            users = db.query(User).filter(
                User.report_preference.in_(['weekly', None]),  # 包含None（默认weekly）
                User.is_active == True
            ).all()
        
        total = len(users)
        success_count = 0
        fail_count = 0
        
        for user in users:
            try:
                products = _get_products_for_user(user.id)
                if _generate_report_for_user(user, products, 'weekly'):
                    success_count += 1
                else:
                    fail_count += 1
            except Exception as user_err:
                logger.error(f"为用户 {user.email} 生成每周报告失败: {user_err}", exc_info=True)
                fail_count += 1
        
        logger.info(f"✅ 每周报告任务完成: 共 {total} 位订阅用户, 成功 {success_count}, 失败 {fail_count}")
        
    except Exception as e:
        logger.error(f"❌ 每周报告任务执行失败: {e}", exc_info=True)
        pass


# ==================== 手动触发报告 ====================

def trigger_daily_report_for_user(user_id: int) -> bool:
    """手动为指定用户触发每日报告（管理员功能）"""
    with get_db_context() as db:
        user = db.query(User).filter(User.id == user_id).first()
    
    if not user:
        logger.warning(f"用户 ID {user_id} 不存在")
        return False
    
    products = _get_products_for_user(user_id)
    return _generate_report_for_user(user, products, 'daily')


def trigger_weekly_report_for_user(user_id: int) -> bool:
    """手动为指定用户触发每周报告（管理员功能）"""
    with get_db_context() as db:
        user = db.query(User).filter(User.id == user_id).first()
    
    if not user:
        logger.warning(f"用户 ID {user_id} 不存在")
        return False
    
    products = _get_products_for_user(user_id)
    return _generate_report_for_user(user, products, 'weekly')


# ==================== 调度器管理 ====================

def start_scheduler():
    """启动定时任务调度器"""
    try:
        if scheduler.running:
            logger.warning("调度器已在运行中，跳过启动")
            return
        
        # 添加每日报告任务 - 每天早上9点(北京时间) = UTC 1:00
        scheduler.add_job(
            func=generate_daily_report,
            trigger=CronTrigger(
                hour=config.REPORT_CRON_HOUR,
                minute=config.REPORT_CRON_MINUTE,
            ),
            id='daily_report',
            name='每日分析报告',
            replace_existing=True,
            max_instances=1,  # 防止并发执行
            misfire_grace_time=3600,  # 错过执行时间1小时内仍可补执行
        )
        
        # 添加每周报告任务 - 每周一早上9点(北京时间)
        scheduler.add_job(
            func=generate_weekly_report,
            trigger=CronTrigger(
                day_of_week='mon',
                hour=config.REPORT_CRON_HOUR,
                minute=config.REPORT_CRON_MINUTE,
            ),
            id='weekly_report',
            name='每周分析报告',
            replace_existing=True,
            max_instances=1,
            misfire_grace_time=7200,
        )
        
        scheduler.start()
        logger.info(f"✅ 定时任务调度器已启动: 每日报告({config.REPORT_CRON_HOUR}:{config.REPORT_CRON_MINUTE:02d} UTC), 每周报告(周一)")
        
    except Exception as e:
        logger.error(f"❌ 启动定时任务调度器失败: {e}", exc_info=True)
        raise


def stop_scheduler():
    """停止定时任务调度器"""
    if scheduler.running:
        scheduler.shutdown(wait=False)
        logger.info("定时任务调度器已停止")
