"""
定时报告生成模块
提供定时任务调度功能，用于自动生成周期性分析报告
"""

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
import logging
from datetime import datetime, timedelta, date
from typing import Dict, List, Optional, Any
from sqlalchemy.orm import Session
from sqlalchemy import text, func

import config
from app.database import SessionLocal, get_db_context
from app.models import User, Dataset, ProductData
from app.services.email_service import email_service

logger = logging.getLogger(__name__)

# 创建调度器实例
scheduler = BackgroundScheduler()


# ==================== 多语言邮件模板 ====================

REPORT_TEMPLATES = {
    'zh': {
        'daily_subject': '📊 {app_name} - 每日营销报告 {date}',
        'daily_title': '每日营销数据报告',
        'weekly_subject': '📊 {app_name} - 每周营销报告 {date}',
        'weekly_title': '每周营销数据报告',
        'summary': '数据概览',
        'total_products': '产品总数',
        'visible_products': '可见产品',
        'hidden_products': '隐藏产品',
        'total_sales': '总销量',
        'total_profit': '总利润',
        'direct_sales': '直接销量',
        'indirect_sales': '间接销量',
        'promoted_sales': '推广销量',
        'vs_yesterday': 'vs 昨日',
        'vs_last_week': 'vs 上周',
        'top_products': '🏆 Top {n} 热销产品',
        'top_products_weekly': '🏆 Top {n} 产品（本周）',
        'product_id': '产品ID',
        'product_name': '产品名称',
        'sales': '销量',
        'profit': '利润',
        'profit_margin': '利润率',
        'anomaly_title': '⚠️ 异常检测提醒',
        'anomaly_count': '共发现 {count} 个异常',
        'anomaly_type': '异常类型',
        'z_score': 'Z-score',
        'low_sales': '销量异常低',
        'high_sales': '销量异常高',
        'ai_insight': '💡 AI 洞察摘要',
        'week_overview': '本周概览',
        'best_day': '最佳表现日',
        'trend': '趋势分析',
        'recommendation': '优化建议',
        'footer': '此报告由 {app_name} 自动生成',
        'footer_unsubscribe': '退订报告',
        'no_data': '暂无数据',
        'no_subscription': '您尚未订阅任何报告',
        'change_preference': '更改订阅设置',
        'greeting': '您好，{username}！',
        'report_intro': '以下是您的 {period} 数据分析报告：',
        'change_up': '↑ {pct}%',
        'change_down': '↓ {pct}%',
        'no_change': '持平',
    },
    'en': {
        'daily_subject': '📊 {app_name} - Daily Marketing Report {date}',
        'daily_title': 'Daily Marketing Report',
        'weekly_subject': '📊 {app_name} - Weekly Marketing Report {date}',
        'weekly_title': 'Weekly Marketing Report',
        'summary': 'Overview',
        'total_products': 'Total Products',
        'visible_products': 'Visible',
        'hidden_products': 'Hidden',
        'total_sales': 'Total Sales',
        'total_profit': 'Total Profit',
        'direct_sales': 'Direct Sales',
        'indirect_sales': 'Indirect Sales',
        'promoted_sales': 'Promoted Sales',
        'vs_yesterday': 'vs Yesterday',
        'vs_last_week': 'vs Last Week',
        'top_products': '🏆 Top {n} Products',
        'top_products_weekly': '🏆 Top {n} Products (This Week)',
        'product_id': 'Product ID',
        'product_name': 'Product Name',
        'sales': 'Sales',
        'profit': 'Profit',
        'profit_margin': 'Margin',
        'anomaly_title': '⚠️ Anomaly Alerts',
        'anomaly_count': '{count} anomalies detected',
        'anomaly_type': 'Type',
        'z_score': 'Z-score',
        'low_sales': 'Abnormally Low Sales',
        'high_sales': 'Abnormally High Sales',
        'ai_insight': '💡 AI Insights',
        'week_overview': 'Week Overview',
        'best_day': 'Best Performance',
        'trend': 'Trend Analysis',
        'recommendation': 'Recommendations',
        'footer': 'Auto-generated by {app_name}',
        'footer_unsubscribe': 'Unsubscribe',
        'no_data': 'No data available',
        'no_subscription': 'You have no active report subscriptions',
        'change_preference': 'Change subscription settings',
        'greeting': 'Hello, {username}!',
        'report_intro': 'Here is your {period} data analysis report:',
        'change_up': '↑ {pct}%',
        'change_down': '↓ {pct}%',
        'no_change': 'No change',
    },
    'fr': {
        'daily_subject': '📊 {app_name} - Rapport Marketing Quotidien {date}',
        'daily_title': 'Rapport Marketing Quotidien',
        'weekly_subject': '📊 {app_name} - Rapport Marketing Hebdomadaire {date}',
        'weekly_title': 'Rapport Marketing Hebdomadaire',
        'summary': 'Aperçu',
        'total_products': 'Total Produits',
        'visible_products': 'Visibles',
        'hidden_products': 'Cachés',
        'total_sales': 'Ventes Totales',
        'total_profit': 'Profit Total',
        'direct_sales': 'Ventes Directes',
        'indirect_sales': 'Ventes Indirectes',
        'promoted_sales': 'Ventes Promues',
        'vs_yesterday': 'vs Hier',
        'vs_last_week': 'vs Semaine Précédente',
        'top_products': '🏆 Top {n} Produits',
        'top_products_weekly': '🏆 Top {n} Produits (Cette Semaine)',
        'product_id': 'ID Produit',
        'product_name': 'Nom du Produit',
        'sales': 'Ventes',
        'profit': 'Profit',
        'profit_margin': 'Marge',
        'anomaly_title': '⚠️ Alertes d\'Anomalies',
        'anomaly_count': '{count} anomalies détectées',
        'anomaly_type': 'Type',
        'z_score': 'Z-score',
        'low_sales': 'Ventes Anormalement Basses',
        'high_sales': 'Ventes Anormalement Élevées',
        'ai_insight': '💡 Perspectives IA',
        'week_overview': 'Aperçu de la Semaine',
        'best_day': 'Meilleure Performance',
        'trend': 'Analyse de Tendance',
        'recommendation': 'Recommandations',
        'footer': 'Généré automatiquement par {app_name}',
        'footer_unsubscribe': 'Se désabonner',
        'no_data': 'Aucune donnée disponible',
        'no_subscription': 'Vous n\'avez aucun abonnement actif',
        'change_preference': 'Modifier les paramètres',
        'greeting': 'Bonjour, {username}!',
        'report_intro': 'Voici votre rapport d\'analyse {period} :',
        'change_up': '↑ {pct}%',
        'change_down': '↓ {pct}%',
        'no_change': 'Stable',
    }
}


# ==================== 到期提醒邮件模板 ====================

EXPIRY_REMINDER_TEMPLATES = {
    'zh': {
        # 3天提醒
        'sub_3day_subject': '⏰ {app_name} - 您的订阅将在3天后到期',
        'sub_3day_title': '订阅到期提醒',
        'sub_3day_greeting': '亲爱的 {username}，',
        'sub_3day_body': '您的 {app_name} 订阅将在 <strong>3 天后</strong> 到期。为了不影响您继续使用我们的服务，请及时续费。',
        'sub_3day_cta': '立即续费',
        # 1天提醒
        'sub_1day_subject': '⚠️ {app_name} - 您的订阅明天到期',
        'sub_1day_title': '订阅到期提醒',
        'sub_1day_greeting': '亲爱的 {username}，',
        'sub_1day_body': '您的 {app_name} 订阅将在 <strong>明天</strong> 到期。续费即可继续享受不间断的服务！',
        'sub_1day_cta': '立即续费',
        # 召回邮件
        'sub_recall_subject': '🎉 {app_name} - 欢迎回来，限时优惠等你拿',
        'sub_recall_title': '欢迎回来',
        'sub_recall_greeting': '亲爱的 {username}，',
        'sub_recall_body': '您的 {app_name} 订阅已过期。为感谢您的支持，我们为您准备了 <strong>限时优惠</strong>，续费可享受特别折扣！',
        'sub_recall_cta': '查看优惠',
        # 试用期3天提醒
        'trial_3day_subject': '⏰ {app_name} - 您的免费试用将在3天后结束',
        'trial_3day_title': '试用期即将结束',
        'trial_3day_greeting': '亲爱的 {username}，',
        'trial_3day_body': '您的 {app_name} 免费试用将在 <strong>3 天后</strong> 结束。升级到付费版，解锁全部高级功能！',
        'trial_3day_cta': '开始使用',
        # 试用期1天提醒
        'trial_1day_subject': '⚠️ {app_name} - 您的免费试用明天结束',
        'trial_1day_title': '试用期即将结束',
        'trial_1day_greeting': '亲爱的 {username}，',
        'trial_1day_body': '您的 {app_name} 免费试用将在 <strong>明天</strong> 结束。立即升级，不错过任何数据洞察！',
        'trial_1day_cta': '升级到Pro',
        # 试用期召回邮件
        'trial_recall_subject': '🎉 {app_name} - 试用期已结束，优惠继续有效',
        'trial_recall_title': '欢迎体验 Pro',
        'trial_recall_greeting': '亲爱的 {username}，',
        'trial_recall_body': '您的 {app_name} 免费试用已结束。我们为您准备了 <strong>首次订阅优惠</strong>，让您以更优惠的价格享受完整服务。',
        'trial_recall_cta': '获取优惠',
        # 通用
        'pricing_page': '定价方案',
        'footer': '此邮件由 {app_name} 自动发送',
        'manage_subscription': '管理订阅',
    },
    'en': {
        # 3天提醒
        'sub_3day_subject': '⏰ {app_name} - Your subscription expires in 3 days',
        'sub_3day_title': 'Subscription Reminder',
        'sub_3day_greeting': 'Dear {username},',
        'sub_3day_body': 'Your {app_name} subscription will expire in <strong>3 days</strong>. Please renew to continue enjoying uninterrupted service.',
        'sub_3day_cta': 'Renew Now',
        # 1天提醒
        'sub_1day_subject': '⚠️ {app_name} - Your subscription expires tomorrow',
        'sub_1day_title': 'Subscription Reminder',
        'sub_1day_greeting': 'Dear {username},',
        'sub_1day_body': 'Your {app_name} subscription will expire <strong>tomorrow</strong>. Renew now to keep your service going!',
        'sub_1day_cta': 'Renew Now',
        # 召回邮件
        'sub_recall_subject': '🎉 {app_name} - Welcome back! Special offer inside',
        'sub_recall_title': 'Welcome Back',
        'sub_recall_greeting': 'Dear {username},',
        'sub_recall_body': 'Your {app_name} subscription has expired. As a valued member, we\'re offering you a <strong>limited-time discount</strong> to come back!',
        'sub_recall_cta': 'View Offer',
        # 试用期3天提醒
        'trial_3day_subject': '⏰ {app_name} - Your free trial ends in 3 days',
        'trial_3day_title': 'Trial Ending Soon',
        'trial_3day_greeting': 'Dear {username},',
        'trial_3day_body': 'Your {app_name} free trial will end in <strong>3 days</strong>. Upgrade to unlock all premium features!',
        'trial_3day_cta': 'Get Started',
        # 试用期1天提醒
        'trial_1day_subject': '⚠️ {app_name} - Your free trial ends tomorrow',
        'trial_1day_title': 'Trial Ending Soon',
        'trial_1day_greeting': 'Dear {username},',
        'trial_1day_body': 'Your {app_name} free trial will end <strong>tomorrow</strong>. Upgrade now to never miss a data insight!',
        'trial_1day_cta': 'Upgrade to Pro',
        # 试用期召回邮件
        'trial_recall_subject': '🎉 {app_name} - Trial ended, special offer available',
        'trial_recall_title': 'Welcome to Pro',
        'trial_recall_greeting': 'Dear {username},',
        'trial_recall_body': 'Your {app_name} free trial has ended. We have a <strong>special first-subscription discount</strong> just for you!',
        'trial_recall_cta': 'Get Offer',
        # 通用
        'pricing_page': 'Pricing',
        'footer': 'This email was sent automatically by {app_name}',
        'manage_subscription': 'Manage Subscription',
    },
    'fr': {
        # 3天提醒
        'sub_3day_subject': '⏰ {app_name} - Votre abonnement expire dans 3 jours',
        'sub_3day_title': 'Rappel d\'abonnement',
        'sub_3day_greeting': 'Cher(e) {username},',
        'sub_3day_body': 'Votre abonnement {app_name} expirera dans <strong>3 jours</strong>. Veuillez renouveler pour continuer à profiter de nos services.',
        'sub_3day_cta': 'Renouveler',
        # 1天提醒
        'sub_1day_subject': '⚠️ {app_name} - Votre abonnement expire demain',
        'sub_1day_title': 'Rappel d\'abonnement',
        'sub_1day_greeting': 'Cher(e) {username},',
        'sub_1day_body': 'Votre abonnement {app_name} expirera <strong>demain</strong>. Renouvelez maintenant pour continuer sans interruption!',
        'sub_1day_cta': 'Renouveler',
        # 召回邮件
        'sub_recall_subject': '🎉 {app_name} - Bon retour! Offre spéciale',
        'sub_recall_title': 'Bon Retour',
        'sub_recall_greeting': 'Cher(e) {username},',
        'sub_recall_body': 'Votre abonnement {app_name} a expiré. En tant que membre fidèle, nous vous proposons une <strong>remise limitée</strong> pour votre retour!',
        'sub_recall_cta': 'Voir l\'Offre',
        # 试用期3天提醒
        'trial_3day_subject': '⏰ {app_name} - Votre essai gratuit se termine dans 3 jours',
        'trial_3day_title': 'Fin d\'Essi',
        'trial_3day_greeting': 'Cher(e) {username},',
        'trial_3day_body': 'Votre essai gratuit {app_name} se terminera dans <strong>3 jours</strong>. Passez à la version payante pour débloquer toutes les fonctionnalités!',
        'trial_3day_cta': 'Commencer',
        # 试用期1天提醒
        'trial_1day_subject': '⚠️ {app_name} - Votre essai gratuit se termine demain',
        'trial_1day_title': 'Fin d\'Essi',
        'trial_1day_greeting': 'Cher(e) {username},',
        'trial_1day_body': 'Votre essai gratuit {app_name} se terminera <strong>demain</strong>. Passez à la version payante pour ne rien manquer!',
        'trial_1day_cta': 'Passer à Pro',
        # 试用期召回邮件
        'trial_recall_subject': '🎉 {app_name} - Essai terminé, offre disponible',
        'trial_recall_title': 'Bienvenue sur Pro',
        'trial_recall_greeting': 'Cher(e) {username},',
        'trial_recall_body': 'Votre essai gratuit {app_name} est terminé. Nous avons une <strong>remise spéciale</strong> pour votre première souscription!',
        'trial_recall_cta': 'Obtenir l\'Offre',
        # 通用
        'pricing_page': 'Tarifs',
        'footer': 'Cet email a été envoyé automatiquement par {app_name}',
        'manage_subscription': 'Gérer l\'abonnement',
    }
}


def _get_user_language(user: User) -> str:
    """从用户信息推断语言偏好，默认为英语"""
    # 简单策略：检查邮箱域名
    email = (user.email or '').lower()
    if email.endswith(('.cn', '.com.cn')):
        return 'zh'
    # 可扩展：从用户设置中读取语言偏好
    return 'en'


def _t(lang: str, key: str, **kwargs) -> str:
    """获取翻译文本"""
    template = REPORT_TEMPLATES.get(lang, REPORT_TEMPLATES['en']).get(key, key)
    return template.format(**kwargs)


def _format_number(n: float) -> str:
    """格式化数字"""
    if isinstance(n, float):
        if abs(n) >= 1000:
            return f"{n:,.1f}"
        return f"{n:.2f}"
    return f"{n:,}"


def _format_profit(p: float) -> str:
    """格式化利润（支持Credits和USD）"""
    credits = f"{p:,.2f} Credits"
    usd = p * 0.0004
    return f"{credits} (${usd:.2f})"


def _calc_change_pct(current: float, previous: float) -> str:
    """计算变化百分比"""
    if previous == 0:
        return '—'
    change = ((current - previous) / abs(previous)) * 100
    if change > 0:
        return f"↑ {change:.1f}%"
    elif change < 0:
        return f"↓ {abs(change):.1f}%"
    return '0%'


def _get_products_for_user(user_id: int) -> List[Dict[str, Any]]:
    """获取用户最新的产品数据"""
    with get_db_context() as db:
        dataset = db.query(Dataset).filter(
            Dataset.user_id == user_id
        ).order_by(Dataset.upload_time.desc()).first()
        
        if not dataset:
            return []
        
        products = db.query(ProductData).filter(
            ProductData.dataset_id == dataset.id
        ).all()
        
        return [
            {
                'product_id': p.product_id,
                'product_name': p.product_name,
                'price': float(p.price or 0),
                'profit': float(p.profit or 0),
                'visible': p.visible,
                'direct_sales': float(p.direct_sales or 0),
                'indirect_sales': float(p.indirect_sales or 0),
                'promoted_sales': float(p.promoted_sales or 0),
                'cart_adds': float(p.cart_adds or 0),
                'wishlist_adds': float(p.wishlist_adds or 0),
                'organic_impressions': float(p.organic_impressions or 0),
                'paid_impressions': float(p.paid_impressions or 0),
            }
            for p in products
        ]


def _analyze_with_analytics(products: List[Dict]) -> Dict:
    """使用 AnalyticsService 进行数据分析"""
    from app.services.analytics import AnalyticsService
    
    if not products:
        return {
            'summary': {},
            'top_products': [],
            'bottom_products': [],
            'anomalies': [],
            'visibility': {},
            'traffic': {},
        }
    
    analytics = AnalyticsService(products)
    
    summary = analytics.get_summary_metrics()
    top_products = analytics.get_top_products(limit=10, metric='profit')
    bottom_products = analytics.get_bottom_products(limit=5, metric='profit')
    anomalies = analytics.detect_sales_anomalies(threshold=2.0)
    visibility = analytics.get_visibility_analysis()
    
    # 计算各产品总销量
    for p in top_products:
        p['total_sales'] = (
            (p.get('direct_sales') or 0) +
            (p.get('indirect_sales') or 0) +
            (p.get('promoted_sales') or 0)
        )
    
    for p in bottom_products:
        p['total_sales'] = (
            (p.get('direct_sales') or 0) +
            (p.get('indirect_sales') or 0) +
            (p.get('promoted_sales') or 0)
        )
    
    return {
        'summary': summary,
        'top_products': top_products,
        'bottom_products': bottom_products,
        'anomalies': anomalies,
        'visibility': visibility,
        'traffic': analytics.get_traffic_analysis(),
    }


def _generate_ai_insight(analysis: Dict, lang: str = 'en') -> str:
    """基于分析数据生成AI洞察"""
    summary = analysis.get('summary', {})
    top_products = analysis.get('top_products', [])
    anomalies = analysis.get('anomalies', [])
    
    insights = []
    t = lambda k, **kw: _t(lang, k, **kw)
    
    # 基于销量的洞察
    total_sales = summary.get('total_sales', 0)
    if total_sales == 0:
        insights.append(t('no_data'))
        return insights[0]
    
    # Top产品洞察
    if top_products:
        best = top_products[0]
        best_name = (best.get('product_name') or best.get('product_id', 'N/A'))[:30]
        best_sales = best.get('total_sales', 0)
        if best_sales > 0:
            insights.append(f"🏆 **{best_name}** — {t('sales')}: {int(best_sales)}")
    
    # 异常检测洞察
    if anomalies:
        low_count = sum(1 for a in anomalies if a.get('z_score', 0) < 0)
        high_count = len(anomalies) - low_count
        if low_count > 0:
            insights.append(f"⚠️ {low_count} {t('low_sales')} {t('product_id')}")
        if high_count > 0:
            insights.append(f"🚀 {high_count} {t('high_sales')}")
    
    # 可见性洞察
    visibility = analysis.get('visibility', {})
    if visibility:
        visible_pct = 0
        total_p = visibility.get('visible', {}).get('count', 0) + visibility.get('hidden', {}).get('count', 0)
        if total_p > 0:
            visible_pct = visibility.get('visible', {}).get('count', 0) / total_p * 100
            if visible_pct < 30:
                insights.append(f"💡 {int(visible_pct)}% products visible — consider increasing visibility for hidden items")
    
    # 利润率洞察
    if top_products:
        high_margin = [p for p in top_products if p.get('profit', 0) > 100]
        if len(high_margin) >= 3:
            insights.append(f"💡 {len(high_margin)}+ high-margin products detected — great pricing strategy!")
    
    return '\n'.join(insights) if insights else t('no_data')


def _build_report_html(
    analysis: Dict,
    tpl: Dict,
    period: str,
    date_str: str,
    username: str,
    top_limit: int = 5
) -> str:
    """构建报告HTML内容"""
    summary = analysis.get('summary', {})
    
    # 计算总销量
    def total_sales(p):
        return int((p.get('direct_sales') or 0) + (p.get('indirect_sales') or 0) + (p.get('promoted_sales') or 0))
    
    top_products = analysis.get('top_products', [])[:top_limit]
    anomalies = analysis.get('anomalies', [])[:5]
    
    # 异常HTML
    anomaly_html = ''
    if anomalies:
        anomaly_items = []
        for a in anomalies:
            product_id = a.get('product_id', 'N/A')
            product_name = (a.get('product_name') or 'N/A')[:30]
            z = abs(a.get('z_score') or 0)
            a_type = tpl.get('low_sales') if a.get('z_score', 0) < 0 else tpl.get('high_sales')
            anomaly_items.append(
                f'<div style="background:#fff3cd;padding:10px;border-radius:5px;margin:5px 0;font-size:13px;">'
                f'<strong>{product_id}</strong> — {product_name}<br>'
                f'<small style="color:#856404">{a_type} (Z: {z:.2f})</small></div>'
            )
        anomaly_html = f'''
        <div style="margin:20px 0;">
            <h2 style="color:#856404;font-size:18px;margin-bottom:10px;">{tpl.get('anomaly_title')}</h2>
            {"".join(anomaly_items)}
        </div>'''
    
    # Top产品行
    def product_row(p, idx):
        name = (p.get('product_name') or p.get('product_id', 'N/A'))[:35]
        sales = total_sales(p)
        profit = p.get('profit', 0)
        margin = (profit / p.get('price', 1) * 100) if p.get('price', 0) > 0 else 0
        return f'''
        <tr style="{'background:#f0f7ff' if idx % 2 == 0 else 'white'}">
            <td style="padding:10px;border-bottom:1px solid #eee;font-size:13px;">{p.get('product_id','')}</td>
            <td style="padding:10px;border-bottom:1px solid #eee;font-size:13px;">{name}</td>
            <td style="padding:10px;border-bottom:1px solid #eee;text-align:center;font-size:13px;">{int(sales)}</td>
            <td style="padding:10px;border-bottom:1px solid #eee;text-align:right;font-size:13px;">{profit:.0f} ({margin:.1f}%)</td>
        </tr>'''
    
    top_rows = ''.join(product_row(p, i) for i, p in enumerate(top_products))
    
    # AI洞察
    ai_insight = _generate_ai_insight(analysis, 'en')  # AI洞察固定用英文
    
    unsubscribe_url = f"{config.SITE_URL}/profile"
    
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 1.6; color: #333; background:#f5f7fa; }}
        .container {{ max-width: 700px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px 20px; border-radius: 16px 16px 0 0; text-align: center; }}
        .header h1 {{ margin: 0 0 8px 0; font-size: 24px; }}
        .header p {{ margin: 0; opacity: 0.9; font-size: 14px; }}
        .body {{ background: white; padding: 30px 25px; border-radius: 0 0 16px 16px; }}
        .greeting {{ font-size: 16px; color: #333; margin-bottom: 20px; }}
        .metrics {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin: 20px 0; }}
        .metric-card {{ background: #f8f9fa; border-radius: 10px; padding: 16px; text-align: center; }}
        .metric-value {{ font-size: 22px; font-weight: bold; color: #667eea; }}
        .metric-label {{ font-size: 12px; color: #888; margin-top: 4px; }}
        .metric-card.highlight {{ background: linear-gradient(135deg, #667eea20, #764ba220); border: 1px solid #667eea40; }}
        .section-title {{ font-size: 16px; font-weight: bold; color: #333; margin: 25px 0 12px 0; padding-bottom: 8px; border-bottom: 2px solid #667eea; }}
        table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
        th {{ background: #f0f2f7; color: #555; padding: 10px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }}
        .ai-insight {{ background: linear-gradient(135deg, #667eea10, #764ba210); border: 1px solid #667eea30; border-radius: 10px; padding: 15px; margin: 20px 0; font-size: 14px; line-height: 1.8; }}
        .footer {{ text-align: center; color: #999; font-size: 12px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; }}
        .footer a {{ color: #667eea; text-decoration: none; }}
        .unsub {{ margin-top: 15px; }}
        @media (max-width: 480px) {{
            .metrics {{ grid-template-columns: 1fr 1fr; gap: 8px; }}
            .metric-value {{ font-size: 18px; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 {config.APP_NAME}</h1>
            <p>{tpl.get(period + '_title')} — {date_str}</p>
        </div>
        <div class="body">
            <p class="greeting">{tpl.get('greeting', username=username or 'Creator')}</p>
            <p>{tpl.get('report_intro', period=tpl.get(period + '_title').lower())}</p>
            
            <!-- 指标卡片 -->
            <div class="metrics">
                <div class="metric-card highlight">
                    <div class="metric-value">{_format_number(summary.get('total_products', 0))}</div>
                    <div class="metric-label">{tpl.get('total_products')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{_format_number(summary.get('total_sales', 0))}</div>
                    <div class="metric-label">{tpl.get('total_sales')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{summary.get('total_profit', 0):,.0f}</div>
                    <div class="metric-label">{tpl.get('total_profit')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{_format_number(summary.get('visible_products', 0))}</div>
                    <div class="metric-label">{tpl.get('visible_products')}</div>
                </div>
            </div>
            
            <!-- 销售额细分 -->
            <div class="metrics">
                <div class="metric-card">
                    <div class="metric-value">{_format_number(summary.get('direct_sales', 0))}</div>
                    <div class="metric-label">{tpl.get('direct_sales')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{_format_number(summary.get('indirect_sales', 0))}</div>
                    <div class="metric-label">{tpl.get('indirect_sales')}</div>
                </div>
            </div>
            
            <!-- Top产品 -->
            {f'''
            <div class="section-title">{tpl.get("top_products", n=top_limit)}</div>
            <table>
                <thead><tr><th>{tpl.get('product_id')}</th><th>{tpl.get('product_name')}</th><th style="text-align:center">{tpl.get('sales')}</th><th style="text-align:right">{tpl.get('profit')} ({tpl.get('profit_margin')})</th></tr></thead>
                <tbody>{top_rows}</tbody>
            </table>
            ''' if top_products else f'<p style="color:#999;font-size:14px;">{tpl.get("no_data")}</p>'}
            
            <!-- 异常检测 -->
            {anomaly_html}
            
            <!-- AI洞察 -->
            <div class="section-title">{tpl.get('ai_insight')}</div>
            <div class="ai-insight">
                {ai_insight}
            </div>
            
            <!-- 页脚 -->
            <div class="footer">
                <p>{tpl.get('footer', app_name=config.APP_NAME)}</p>
                <div class="unsub">
                    <a href="{unsubscribe_url}">{tpl.get('change_preference')}</a>
                    &nbsp;|&nbsp;
                    <a href="{unsubscribe_url}">{tpl.get('footer_unsubscribe')}</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
    """
    return html


# ==================== 报告生成核心逻辑 ====================

def _generate_report_for_user(
    user: User,
    products: List[Dict],
    report_type: str  # 'daily' or 'weekly'
) -> bool:
    """
    为单个用户生成并发送报告
    Returns: 是否发送成功
    """
    lang = _get_user_language(user)
    tpl = REPORT_TEMPLATES.get(lang, REPORT_TEMPLATES['en'])
    
    today = date.today()
    date_str = today.strftime('%Y-%m-%d')
    
    if report_type == 'daily':
        subject = tpl.get('daily_subject', app_name=config.APP_NAME, date=date_str)
    else:
        # 每周报告显示本周范围
        week_start = today - timedelta(days=today.weekday())
        week_end = week_start + timedelta(days=6)
        date_str = f"{week_start.strftime('%m/%d')} - {week_end.strftime('%m/%d')}"
        subject = tpl.get('weekly_subject', app_name=config.APP_NAME, date=date_str)
    
    if not products:
        logger.info(f"用户 {user.email} 没有产品数据，跳过{report_type}报告")
        return False
    
    # 分析数据
    analysis = _analyze_with_analytics(products)
    
    # 构建HTML
    top_limit = 5 if report_type == 'daily' else 10
    html_content = _build_report_html(
        analysis=analysis,
        tpl=tpl,
        period=report_type,
        date_str=date_str,
        username=user.username or user.email.split('@')[0],
        top_limit=top_limit
    )
    
    # 发送邮件
    success, msg = email_service.send_report(
        to_emails=[user.email],
        subject=subject,
        html_content=html_content
    )
    
    if success:
        logger.info(f"{report_type.capitalize()}报告已发送给 {user.email}: {msg}")
    else:
        logger.warning(f"{report_type.capitalize()}报告发送失败 {user.email}: {msg}")
    
    return success


def generate_daily_report():
    """
    生成每日报告的定时任务
    为所有订阅每日报告的用户生成并发送报告
    """
    logger.info(f"🕐 定时任务执行: 生成每日报告 - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        with get_db_context() as db:
            # 查找所有订阅每日报告的用户
            users = db.query(User).filter(
                User.report_preference == 'daily',
                User.is_active == True
            ).all()
        
        total = len(users)
        success_count = 0
        fail_count = 0
        
        for user in users:
            try:
                products = _get_products_for_user(user.id)
                if _generate_report_for_user(user, products, 'daily'):
                    success_count += 1
                else:
                    fail_count += 1
            except Exception as user_err:
                logger.error(f"为用户 {user.email} 生成每日报告失败: {user_err}", exc_info=True)
                fail_count += 1
        
        logger.info(f"✅ 每日报告任务完成: 共 {total} 位订阅用户, 成功 {success_count}, 失败 {fail_count}")
        
    except Exception as e:
        logger.error(f"❌ 每日报告任务执行失败: {e}", exc_info=True)
        # 不向上抛出，避免调度器崩溃
        pass


def generate_weekly_report():
    """
    生成每周报告的定时任务
    为所有订阅每周报告的用户生成并发送报告
    """
    logger.info(f"🕐 定时任务执行: 生成每周报告 - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        # 每周报告只在周一发送
        today = date.today()
        if today.weekday() != 0:  # 0 = Monday
            logger.info(f"今天不是周一，跳过每周报告（将在周一执行）")
            return
        
        with get_db_context() as db:
            # 查找所有订阅每周报告的用户（包括默认用户）
            users = db.query(User).filter(
                User.report_preference.in_(['weekly', None]),  # 包含None（默认weekly）
                User.is_active == True
            ).all()
        
        total = len(users)
        success_count = 0
        fail_count = 0
        
        for user in users:
            try:
                products = _get_products_for_user(user.id)
                if _generate_report_for_user(user, products, 'weekly'):
                    success_count += 1
                else:
                    fail_count += 1
            except Exception as user_err:
                logger.error(f"为用户 {user.email} 生成每周报告失败: {user_err}", exc_info=True)
                fail_count += 1
        
        logger.info(f"✅ 每周报告任务完成: 共 {total} 位订阅用户, 成功 {success_count}, 失败 {fail_count}")
        
    except Exception as e:
        logger.error(f"❌ 每周报告任务执行失败: {e}", exc_info=True)
        pass


# ==================== 手动触发报告 ====================

def trigger_daily_report_for_user(user_id: int) -> bool:
    """手动为指定用户触发每日报告（管理员功能）"""
    with get_db_context() as db:
        user = db.query(User).filter(User.id == user_id).first()
    
    if not user:
        logger.warning(f"用户 ID {user_id} 不存在")
        return False
    
    products = _get_products_for_user(user_id)
    return _generate_report_for_user(user, products, 'daily')


def trigger_weekly_report_for_user(user_id: int) -> bool:
    """手动为指定用户触发每周报告（管理员功能）"""
    with get_db_context() as db:
        user = db.query(User).filter(User.id == user_id).first()
    
    if not user:
        logger.warning(f"用户 ID {user_id} 不存在")
        return False
    
    products = _get_products_for_user(user_id)
    return _generate_report_for_user(user, products, 'weekly')


# ==================== 调度器管理 ====================

# ==================== 异常推荐行为检测 ====================

def check_suspicious_referral_activity():
    """
    检测异常推荐行为
    
    检测规则：
    1. 同一推荐码7天内被使用超过5次 → 标记异常
    2. 同一推荐码总使用超过20次 → 暂停该推荐码
    3. 通知管理员
    """
    try:
        with get_db_context() as db:
            from app.models import User
            from app.database import UserRepository
            
            user_repo = UserRepository(db)
            suspicious_codes = []
            suspended_codes = []
            
            # 获取所有有推荐人的用户
            users_with_referrer = db.query(User).filter(
                User.referred_by.isnot(None)
            ).all()
            
            # 按推荐码分组统计
            referral_stats = {}
            for user in users_with_referrer:
                if user.referred_by:
                    if user.referred_by not in referral_stats:
                        referral_stats[user.referred_by] = {
                            'total': 0,
                            'recent': 0,
                            'referrer_id': None
                        }
                    referral_stats[user.referred_by]['total'] += 1
                    
                    # 统计7天内的使用
                    if user.created_at >= datetime.utcnow() - timedelta(days=7):
                        referral_stats[user.referred_by]['recent'] += 1
                    
                    referral_stats[user.referred_by]['referrer_id'] = user.referred_by
            
            # 检测异常
            for code, stats in referral_stats.items():
                referrer = user_repo.get_by_referral_code(code)
                if not referrer:
                    continue
                
                # 规则1: 7天内超过5次使用
                if stats['recent'] > 5:
                    suspicious_codes.append({
                        'code': code,
                        'referrer_email': referrer.email,
                        'recent_uses': stats['recent'],
                        'total_uses': stats['total'],
                        'reason': f"7天内使用{stats['recent']}次，超过阈值5次"
                    })
                
                # 规则2: 总使用超过20次
                if stats['total'] > 20 and not referrer.referral_suspended:
                    user_repo.suspend_referral_code(referrer.id, True)
                    suspended_codes.append({
                        'code': code,
                        'referrer_email': referrer.email,
                        'total_uses': stats['total'],
                        'reason': f"总使用{stats['total']}次，超过阈值20次"
                    })
                    logger.warning(f"推荐码 {code} 因使用过多({stats['total']}次)已被自动暂停")
            
            # 发送管理员通知
            if suspicious_codes or suspended_codes:
                _send_antifraud_admin_alert(suspicious_codes, suspended_codes)
            
            logger.info(f"推荐系统异常检测完成: {len(suspicious_codes)}个可疑, {len(suspended_codes)}个已暂停")
            return {
                'suspicious': suspicious_codes,
                'suspended': suspended_codes
            }
    
    except Exception as e:
        logger.error(f"异常推荐行为检测失败: {e}", exc_info=True)
        return {'error': '检测失败，请稍后重试'}


def _send_antifraud_admin_alert(suspicious_codes: list, suspended_codes: list):
    """
    发送管理员防欺诈警报
    
    Args:
        suspicious_codes: 可疑推荐码列表
        suspended_codes: 已暂停的推荐码列表
    """
    try:
        # 获取管理员邮箱列表
        admin_emails = config.ADMIN_EMAIL
        
        if not admin_emails:
            return
        
        if isinstance(admin_emails, str):
            admin_emails = [admin_emails]
        
        # 构建邮件内容
        subject = f"[IMVU Analytics] 推荐系统异常检测报告 - {len(suspicious_codes)}可疑, {len(suspended_codes)}暂停"
        
        body = f"""
        <h2>推荐系统异常检测报告</h2>
        <p>检测时间: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
        
        <h3>⚠️ 可疑推荐码 ({len(suspicious_codes)}个)</h3>
        <ul>
        """
        for item in suspicious_codes:
            body += f"<li><strong>{item['code']}</strong> ({item['referrer_email']}): {item['reason']}</li>"
        body += "</ul>"
        
        if suspended_codes:
            body += """
            <h3>🔒 已暂停的推荐码 ({len(suspended_codes)}个)</h3>
            <ul>
            """
            for item in suspended_codes:
                body += f"<li><strong>{item['code']}</strong> ({item['referrer_email']}): {item['reason']}</li>"
            body += "</ul>"
        
        body += f"""
        <hr>
        <p>请登录管理后台查看详情: {config.SITE_URL}/admin</p>
        <p><small>此邮件由 {config.APP_NAME} 自动发送</small></p>
        """
        
        # 发送邮件
        from app.services.email_service import email_service
        for admin_email in admin_emails:
            try:
                email_service.send_email(
                    to_email=admin_email,
                    subject=subject,
                    html_content=body
                )
            except Exception as email_err:
                logger.warning(f"发送管理员警报邮件失败: {email_err}")
    
    except Exception as e:
        logger.error(f"发送防欺诈警报失败: {e}")


def calculate_industry_benchmarks():
    """
    定时计算行业基准数据
    每天凌晨执行，聚合所有用户的产品数据生成行业基准
    """
    logger.info("开始执行行业基准计算任务...")
    
    try:
        from app.services.benchmark import benchmark_service
        
        with get_db_context() as db:
            result = benchmark_service.calculate_benchmarks(db)
            
            if result.get('status') == 'success':
                logger.info(f"行业基准计算成功: 处理了 {result.get('categories_processed', 0)} 个类别, "
                          f"共 {result.get('total_products', 0)} 个产品, "
                          f"参与用户 {result.get('total_users', 0)} 人")
                
                # 通知订阅用户基准数据已更新
                _notify_subscribers_benchmark_updated()
            else:
                logger.warning(f"行业基准计算未完成: {result.get('status')}")
                
    except Exception as e:
        logger.error(f"行业基准计算任务失败: {e}", exc_info=True)


def _notify_subscribers_benchmark_updated():
    """
    通知订阅用户行业基准已更新
    """
    try:
        # 获取所有活跃订阅用户
        with get_db_context() as db:
            from app.models import User
            
            subscribers = db.query(User).filter(
                User.subscription_status == 'active',
                User.is_active == True,
                User.opt_out_benchmark == False
            ).all()
            
            if not subscribers:
                return
            
            admin_emails = config.ADMIN_EMAIL.split(',') if config.ADMIN_EMAIL else []
            
            # 构建邮件内容
            subject = f"📊 {config.APP_NAME} - 行业基准数据已更新"
            
            body = f"""
            <h2>行业基准数据更新通知</h2>
            <p>您好，</p>
            <p>IMVU Analytics 的行业基准数据已更新。您的产品现在可以与最新的行业数据进行对比。</p>
            <p><a href="{config.SITE_URL}/benchmark" style="background-color: #667eea; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">查看竞品分析</a></p>
            <hr>
            <p><small>此邮件由 {config.APP_NAME} 自动发送</small></p>
            """
            
            # 发送邮件给管理员（让他们知道更新了）
            from app.services.email_service import email_service
            for admin_email in admin_emails:
                try:
                    email_service.send_email(
                        to_email=admin_email,
                        subject=f"[基准更新] {subject}",
                        html_content=f"<p>行业基准数据已更新，共有 {len(subscribers)} 位订阅用户。</p>{body}"
                    )
                except Exception as email_err:
                    logger.warning(f"发送基准更新通知邮件失败: {email_err}")
                    
    except Exception as e:
        logger.error(f"发送基准更新通知失败: {e}")


def start_scheduler():
    """启动定时任务调度器"""
    try:
        if scheduler.running:
            logger.warning("调度器已在运行中，跳过启动")
            return
        
        # 添加每日报告任务 - 每天早上9点(北京时间) = UTC 1:00
        scheduler.add_job(
            func=generate_daily_report,
            trigger=CronTrigger(
                hour=config.REPORT_CRON_HOUR,
                minute=config.REPORT_CRON_MINUTE,
            ),
            id='daily_report',
            name='每日分析报告',
            replace_existing=True,
            max_instances=1,  # 防止并发执行
            misfire_grace_time=3600,  # 错过执行时间1小时内仍可补执行
        )
        
        # 添加每周报告任务 - 每周一早上9点(北京时间)
        scheduler.add_job(
            func=generate_weekly_report,
            trigger=CronTrigger(
                day_of_week='mon',
                hour=config.REPORT_CRON_HOUR,
                minute=config.REPORT_CRON_MINUTE,
            ),
            id='weekly_report',
            name='每周分析报告',
            replace_existing=True,
            max_instances=1,
            misfire_grace_time=7200,
        )
        
        # 添加订阅到期提醒任务 - 每天 UTC 1:00 (北京时间 9:00)
        scheduler.add_job(
            func=check_subscription_expiry,
            trigger=CronTrigger(
                hour=1,  # UTC 1:00 = 北京时间 9:00
                minute=0,
            ),
            id='subscription_expiry_check',
            name='订阅到期提醒',
            replace_existing=True,
            max_instances=1,
            misfire_grace_time=3600,
        )
        
        # 添加推荐系统异常检测任务 - 每6小时检查一次
        scheduler.add_job(
            func=check_suspicious_referral_activity,
            trigger=CronTrigger(
                hour='*/6',  # 每6小时
                minute=0,
            ),
            id='referral_antifraud_check',
            name='推荐系统异常检测',
            replace_existing=True,
            max_instances=1,
            misfire_grace_time=1800,
        )
        
        # 添加行业基准计算任务 - 每天凌晨 UTC 2:00 (北京时间 10:00)
        scheduler.add_job(
            func=calculate_industry_benchmarks,
            trigger=CronTrigger(
                hour=2,  # UTC 2:00 = 北京时间 10:00
                minute=0,
            ),
            id='industry_benchmark_calculation',
            name='行业基准计算',
            replace_existing=True,
            max_instances=1,
            misfire_grace_time=3600,
        )
        
        scheduler.start()
        logger.info(f"✅ 定时任务调度器已启动: 每日报告({config.REPORT_CRON_HOUR}:{config.REPORT_CRON_MINUTE:02d} UTC), 每周报告(周一), 到期提醒(09:00 北京时间), 推荐异常检测(每6小时)")
        
    except Exception as e:
        logger.error(f"❌ 启动定时任务调度器失败: {e}", exc_info=True)
        raise


def stop_scheduler():
    """停止定时任务调度器"""
    if scheduler.running:
        scheduler.shutdown(wait=False)
        logger.info("定时任务调度器已停止")


# ==================== 到期提醒邮件发送函数 ====================

def _build_expiry_reminder_html(
    tpl: dict,
    reminder_type: str,  # 'sub_3day', 'sub_1day', 'sub_recall', 'trial_3day', 'trial_1day', 'trial_recall'
    username: str,
    lang: str = 'en'
) -> str:
    """构建到期提醒邮件HTML"""
    pricing_url = f"{config.SITE_URL}/pricing"
    manage_url = f"{config.SITE_URL}/profile"
    
    # 根据类型选择颜色主题
    if 'recall' in reminder_type:
        theme_color = '#28a745'  # 绿色-召回
        theme_gradient = 'linear-gradient(135deg, #28a745 0%, #20c997 100%)'
    elif '1day' in reminder_type:
        theme_color = '#ffc107'  # 黄色-紧急
        theme_gradient = 'linear-gradient(135deg, #ffc107 0%, #fd7e14 100%)'
    else:
        theme_color = '#667eea'  # 蓝色-常规
        theme_gradient = 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
    
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 1.6; color: #333; background:#f5f7fa; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: {theme_gradient}; color: white; padding: 35px 20px; border-radius: 16px 16px 0 0; text-align: center; }}
        .header h1 {{ margin: 0 0 8px 0; font-size: 26px; font-weight: 600; }}
        .header .icon {{ font-size: 48px; margin-bottom: 10px; }}
        .body {{ background: white; padding: 35px 30px; border-radius: 0 0 16px 16px; }}
        .greeting {{ font-size: 17px; color: #333; margin-bottom: 20px; font-weight: 500; }}
        .message {{ font-size: 16px; color: #555; margin-bottom: 30px; line-height: 1.8; }}
        .highlight {{ color: {theme_color}; font-weight: 600; }}
        .cta-container {{ text-align: center; margin: 30px 0; }}
        .cta-button {{ display: inline-block; background: {theme_gradient}; color: white; padding: 16px 40px; text-decoration: none; border-radius: 50px; font-size: 16px; font-weight: 600; box-shadow: 0 4px 15px rgba(0,0,0,0.2); transition: transform 0.2s; }}
        .cta-button:hover {{ transform: translateY(-2px); }}
        .features {{ background: #f8f9fa; border-radius: 12px; padding: 20px; margin: 25px 0; }}
        .features h3 {{ margin: 0 0 15px 0; font-size: 15px; color: #555; }}
        .feature-item {{ display: flex; align-items: center; margin: 10px 0; font-size: 14px; color: #666; }}
        .feature-item span {{ margin-right: 10px; }} 
        .footer {{ text-align: center; color: #999; font-size: 12px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; }}
        .footer a {{ color: #667eea; text-decoration: none; }}
        .footer-links {{ margin-top: 15px; }}
        .footer-links a {{ margin: 0 10px; color: #888; }}
        @media (max-width: 480px) {{
            .container {{ padding: 10px; }}
            .body {{ padding: 25px 20px; }}
            .header {{ padding: 25px 15px; }}
            .header h1 {{ font-size: 22px; }}
            .cta-button {{ padding: 14px 30px; font-size: 15px; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="icon">{'🎉' if 'recall' in reminder_type else ('⚠️' if '1day' in reminder_type else '⏰')}</div>
            <h1>{tpl.get(reminder_type + '_title', '')}</h1>
        </div>
        <div class="body">
            <p class="greeting">{tpl.get(reminder_type + '_greeting', '').format(username=username)}</p>
            <p class="message">{tpl.get(reminder_type + '_body', '').format(app_name=config.APP_NAME)}</p>
            
            <div class="cta-container">
                <a href="{pricing_url}" class="cta-button">{tpl.get(reminder_type + '_cta', '')}</a>
            </div>
            
            <div class="features">
                <h3>{tpl.get('pricing_page', 'Pricing')}</h3>
                <div class="feature-item"><span>✓</span> {'Unlimited reports & data exports' if lang == 'en' else ('无限制报告和数据导出' if lang == 'zh' else 'Rapports et export illimités')}</div>
                <div class="feature-item"><span>✓</span> {'Advanced AI analytics & insights' if lang == 'en' else ('高级AI分析与洞察' if lang == 'zh' else 'Analyses IA avancées')}</div>
                <div class="feature-item"><span>✓</span> {'Priority email support' if lang == 'en' else ('优先邮件支持' if lang == 'zh' else 'Support email prioritaire')}</div>
            </div>
            
            <div class="footer">
                <p>{tpl.get('footer', '').format(app_name=config.APP_NAME)}</p>
                <div class="footer-links">
                    <a href="{pricing_url}">{tpl.get('pricing_page', 'Pricing')}</a>
                    <span>|</span>
                    <a href="{manage_url}">{tpl.get('manage_subscription', 'Manage Subscription')}</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
    """
    return html


def _send_expiry_reminder(
    user: User,
    reminder_type: str  # 'sub_3day', 'sub_1day', 'sub_recall', 'trial_3day', 'trial_1day', 'trial_recall'
) -> bool:
    """
    发送到期提醒邮件给单个用户
    Returns: 是否发送成功
    """
    lang = _get_user_language(user)
    tpl = EXPIRY_REMINDER_TEMPLATES.get(lang, EXPIRY_REMINDER_TEMPLATES['en'])
    
    # 构建主题和内容
    subject = tpl.get(reminder_type + '_subject', '').format(app_name=config.APP_NAME)
    username_display = user.username or user.email.split('@')[0]
    html_content = _build_expiry_reminder_html(tpl, reminder_type, username_display, lang)
    
    # 发送邮件
    success, msg = email_service.send_report(
        to_emails=[user.email],
        subject=subject,
        html_content=html_content
    )
    
    if success:
        logger.info(f"到期提醒({reminder_type})已发送给 {user.email}")
    else:
        logger.warning(f"到期提醒({reminder_type})发送失败 {user.email}: {msg}")
    
    return success


def _reset_reminder_flags(user: User, is_trial: bool = False) -> None:
    """重置提醒标志（在续费后调用）"""
    if is_trial:
        user.trial_reminder_3day_sent = False
        user.trial_reminder_1day_sent = False
        user.trial_reminder_recall_sent = False
    else:
        user.reminder_3day_sent = False
        user.reminder_1day_sent = False
        user.reminder_recall_sent = False


# ==================== 到期提醒定时任务 ====================

def check_subscription_expiry():
    """
    检查订阅到期情况并发送提醒
    每天 UTC 1:00（北京9:00）执行
    
    检查逻辑：
    1. 订阅到期前3天 -> 发送3天提醒
    2. 订阅到期前1天 -> 发送1天提醒
    3. 订阅过期后7天 -> 发送召回邮件
    4. 试用期同样逻辑
    """
    logger.info(f"🕐 定时任务执行: 检查订阅到期提醒 - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    try:
        today = datetime.utcnow().date()
        
        with get_db_context() as db:
            # ===== 付费订阅用户提醒 =====
            
            # 1. 订阅即将到期（3天）
            expiring_3day = db.query(User).filter(
                User.subscription_status == 'active',
                User.is_active == True,
                User.is_whitelisted == False,
                User.reminder_3day_sent == False,
                User.subscription_end_date != None,
                # subscription_end_date 在今天+2天 到 今天+4天 之间（即3天后到期）
                func.date(User.subscription_end_date) >= today + timedelta(days=2),
                func.date(User.subscription_end_date) <= today + timedelta(days=4),
            ).all()
            
            # 2. 订阅即将到期（1天）
            expiring_1day = db.query(User).filter(
                User.subscription_status == 'active',
                User.is_active == True,
                User.is_whitelisted == False,
                User.reminder_1day_sent == False,
                User.subscription_end_date != None,
                # subscription_end_date 在今天 到 今天+1天 之间（即明天到期）
                func.date(User.subscription_end_date) >= today,
                func.date(User.subscription_end_date) <= today + timedelta(days=1),
            ).all()
            
            # 3. 订阅已过期（7天内）
            expired_7day = db.query(User).filter(
                User.subscription_status.in_(['active', 'expired', 'canceled']),
                User.is_active == True,
                User.is_whitelisted == False,
                User.reminder_recall_sent == False,
                User.subscription_end_date != None,
                # subscription_end_date 在今天-7天 到 今天-1天 之间（即过期1-7天）
                func.date(User.subscription_end_date) >= today - timedelta(days=7),
                func.date(User.subscription_end_date) <= today - timedelta(days=1),
            ).all()
            
            # ===== 试用期用户提醒 =====
            
            # 4. 试用期即将到期（3天）
            trial_expiring_3day = db.query(User).filter(
                User.trial_end_date != None,
                User.subscription_status == 'none',  # 试用期用户
                User.is_active == True,
                User.trial_reminder_3day_sent == False,
                # trial_end_date 在今天+2天 到 今天+4天 之间
                func.date(User.trial_end_date) >= today + timedelta(days=2),
                func.date(User.trial_end_date) <= today + timedelta(days=4),
            ).all()
            
            # 5. 试用期即将到期（1天）
            trial_expiring_1day = db.query(User).filter(
                User.trial_end_date != None,
                User.subscription_status == 'none',
                User.is_active == True,
                User.trial_reminder_1day_sent == False,
                # trial_end_date 在今天 到 今天+1天 之间
                func.date(User.trial_end_date) >= today,
                func.date(User.trial_end_date) <= today + timedelta(days=1),
            ).all()
            
            # 6. 试用期已过期（7天内）
            trial_expired_7day = db.query(User).filter(
                User.trial_end_date != None,
                User.subscription_status == 'none',
                User.is_active == True,
                User.trial_reminder_recall_sent == False,
                # trial_end_date 在今天-7天 到 今天-1天 之间
                func.date(User.trial_end_date) >= today - timedelta(days=7),
                func.date(User.trial_end_date) <= today - timedelta(days=1),
            ).all()
        
        # 统计发送结果
        stats = {
            'sub_3day': {'found': len(expiring_3day), 'sent': 0, 'failed': 0},
            'sub_1day': {'found': len(expiring_1day), 'sent': 0, 'failed': 0},
            'sub_recall': {'found': len(expired_7day), 'sent': 0, 'failed': 0},
            'trial_3day': {'found': len(trial_expiring_3day), 'sent': 0, 'failed': 0},
            'trial_1day': {'found': len(trial_expiring_1day), 'sent': 0, 'failed': 0},
            'trial_recall': {'found': len(trial_expired_7day), 'sent': 0, 'failed': 0},
        }
        
        # 发送邮件（付费订阅）
        for user in expiring_3day:
            try:
                if _send_expiry_reminder(user, 'sub_3day'):
                    stats['sub_3day']['sent'] += 1
                    with get_db_context() as db:
                        db_user = db.query(User).filter(User.id == user.id).first()
                        if db_user:
                            db_user.reminder_3day_sent = True
                            db_user.last_reminder_sent = datetime.utcnow()
                else:
                    stats['sub_3day']['failed'] += 1
            except Exception as e:
                logger.error(f"发送订阅3天提醒给 {user.email} 失败: {e}")
                stats['sub_3day']['failed'] += 1
        
        for user in expiring_1day:
            try:
                if _send_expiry_reminder(user, 'sub_1day'):
                    stats['sub_1day']['sent'] += 1
                    with get_db_context() as db:
                        db_user = db.query(User).filter(User.id == user.id).first()
                        if db_user:
                            db_user.reminder_1day_sent = True
                            db_user.last_reminder_sent = datetime.utcnow()
                else:
                    stats['sub_1day']['failed'] += 1
            except Exception as e:
                logger.error(f"发送订阅1天提醒给 {user.email} 失败: {e}")
                stats['sub_1day']['failed'] += 1
        
        for user in expired_7day:
            try:
                if _send_expiry_reminder(user, 'sub_recall'):
                    stats['sub_recall']['sent'] += 1
                    with get_db_context() as db:
                        db_user = db.query(User).filter(User.id == user.id).first()
                        if db_user:
                            db_user.reminder_recall_sent = True
                            db_user.last_reminder_sent = datetime.utcnow()
                else:
                    stats['sub_recall']['failed'] += 1
            except Exception as e:
                logger.error(f"发送订阅召回邮件给 {user.email} 失败: {e}")
                stats['sub_recall']['failed'] += 1
        
        # 发送邮件（试用期）
        for user in trial_expiring_3day:
            try:
                if _send_expiry_reminder(user, 'trial_3day'):
                    stats['trial_3day']['sent'] += 1
                    with get_db_context() as db:
                        db_user = db.query(User).filter(User.id == user.id).first()
                        if db_user:
                            db_user.trial_reminder_3day_sent = True
                else:
                    stats['trial_3day']['failed'] += 1
            except Exception as e:
                logger.error(f"发送试用期3天提醒给 {user.email} 失败: {e}")
                stats['trial_3day']['failed'] += 1
        
        for user in trial_expiring_1day:
            try:
                if _send_expiry_reminder(user, 'trial_1day'):
                    stats['trial_1day']['sent'] += 1
                    with get_db_context() as db:
                        db_user = db.query(User).filter(User.id == user.id).first()
                        if db_user:
                            db_user.trial_reminder_1day_sent = True
                else:
                    stats['trial_1day']['failed'] += 1
            except Exception as e:
                logger.error(f"发送试用期1天提醒给 {user.email} 失败: {e}")
                stats['trial_1day']['failed'] += 1
        
        for user in trial_expired_7day:
            try:
                if _send_expiry_reminder(user, 'trial_recall'):
                    stats['trial_recall']['sent'] += 1
                    with get_db_context() as db:
                        db_user = db.query(User).filter(User.id == user.id).first()
                        if db_user:
                            db_user.trial_reminder_recall_sent = True
                else:
                    stats['trial_recall']['failed'] += 1
            except Exception as e:
                logger.error(f"发送试用期召回邮件给 {user.email} 失败: {e}")
                stats['trial_recall']['failed'] += 1
        
        # 汇总日志
        total_found = sum(s['found'] for s in stats.values())
        total_sent = sum(s['sent'] for s in stats.values())
        total_failed = sum(s['failed'] for s in stats.values())
        
        logger.info(f"✅ 订阅到期提醒任务完成:")
        logger.info(f"   付费订阅-3天提醒: 发现{stats['sub_3day']['found']}, 发送{stats['sub_3day']['sent']}, 失败{stats['sub_3day']['failed']}")
        logger.info(f"   付费订阅-1天提醒: 发现{stats['sub_1day']['found']}, 发送{stats['sub_1day']['sent']}, 失败{stats['sub_1day']['failed']}")
        logger.info(f"   付费订阅-召回邮件: 发现{stats['sub_recall']['found']}, 发送{stats['sub_recall']['sent']}, 失败{stats['sub_recall']['failed']}")
        logger.info(f"   试用期-3天提醒: 发现{stats['trial_3day']['found']}, 发送{stats['trial_3day']['sent']}, 失败{stats['trial_3day']['failed']}")
        logger.info(f"   试用期-1天提醒: 发现{stats['trial_1day']['found']}, 发送{stats['trial_1day']['sent']}, 失败{stats['trial_1day']['failed']}")
        logger.info(f"   试用期-召回邮件: 发现{stats['trial_recall']['found']}, 发送{stats['trial_recall']['sent']}, 失败{stats['trial_recall']['failed']}")
        logger.info(f"   合计: 发现{total_found}, 发送{total_sent}, 失败{total_failed}")
        
    except Exception as e:
        logger.error(f"❌ 订阅到期提醒任务执行失败: {e}", exc_info=True)
        pass


# 在调度器中添加到期提醒任务（已在 start_scheduler 中添加）


# ==================== 管理后台统计函数 ====================

def get_reminder_stats() -> dict:
    """
    获取提醒发送统计（供管理后台使用）
    Returns: 统计数据字典
    """
    try:
        with get_db_context() as db:
            # 统计各类型提醒的发送情况
            total_users = db.query(User).filter(User.is_active == True).count()
            
            # 已发送各种提醒的用户数
            sub_3day_sent = db.query(User).filter(User.reminder_3day_sent == True).count()
            sub_1day_sent = db.query(User).filter(User.reminder_1day_sent == True).count()
            sub_recall_sent = db.query(User).filter(User.reminder_recall_sent == True).count()
            
            trial_3day_sent = db.query(User).filter(User.trial_reminder_3day_sent == True).count()
            trial_1day_sent = db.query(User).filter(User.trial_reminder_1day_sent == True).count()
            trial_recall_sent = db.query(User).filter(User.trial_reminder_recall_sent == True).count()
            
            # 待发送提醒的用户（即将到期/已过期未发提醒）
            today = datetime.utcnow().date()
            
            pending_sub_3day = db.query(User).filter(
                User.subscription_status == 'active',
                User.is_active == True,
                User.is_whitelisted == False,
                User.reminder_3day_sent == False,
                User.subscription_end_date != None,
                func.date(User.subscription_end_date) >= today + timedelta(days=2),
                func.date(User.subscription_end_date) <= today + timedelta(days=4),
            ).count()
            
            pending_sub_1day = db.query(User).filter(
                User.subscription_status == 'active',
                User.is_active == True,
                User.is_whitelisted == False,
                User.reminder_1day_sent == False,
                User.subscription_end_date != None,
                func.date(User.subscription_end_date) >= today,
                func.date(User.subscription_end_date) <= today + timedelta(days=1),
            ).count()
            
            pending_sub_recall = db.query(User).filter(
                User.subscription_status.in_(['active', 'expired', 'canceled']),
                User.is_active == True,
                User.is_whitelisted == False,
                User.reminder_recall_sent == False,
                User.subscription_end_date != None,
                func.date(User.subscription_end_date) >= today - timedelta(days=7),
                func.date(User.subscription_end_date) <= today - timedelta(days=1),
            ).count()
            
            pending_trial_3day = db.query(User).filter(
                User.trial_end_date != None,
                User.subscription_status == 'none',
                User.is_active == True,
                User.trial_reminder_3day_sent == False,
                func.date(User.trial_end_date) >= today + timedelta(days=2),
                func.date(User.trial_end_date) <= today + timedelta(days=4),
            ).count()
            
            pending_trial_1day = db.query(User).filter(
                User.trial_end_date != None,
                User.subscription_status == 'none',
                User.is_active == True,
                User.trial_reminder_1day_sent == False,
                func.date(User.trial_end_date) >= today,
                func.date(User.trial_end_date) <= today + timedelta(days=1),
            ).count()
            
            pending_trial_recall = db.query(User).filter(
                User.trial_end_date != None,
                User.subscription_status == 'none',
                User.is_active == True,
                User.trial_reminder_recall_sent == False,
                func.date(User.trial_end_date) >= today - timedelta(days=7),
                func.date(User.trial_end_date) <= today - timedelta(days=1),
            ).count()
            
            return {
                'total_users': total_users,
                'sent': {
                    'sub_3day': sub_3day_sent,
                    'sub_1day': sub_1day_sent,
                    'sub_recall': sub_recall_sent,
                    'trial_3day': trial_3day_sent,
                    'trial_1day': trial_1day_sent,
                    'trial_recall': trial_recall_sent,
                },
                'pending': {
                    'sub_3day': pending_sub_3day,
                    'sub_1day': pending_sub_1day,
                    'sub_recall': pending_sub_recall,
                    'trial_3day': pending_trial_3day,
                    'trial_1day': pending_trial_1day,
                    'trial_recall': pending_trial_recall,
                }
            }
    except Exception as e:
        logger.error(f"获取提醒统计失败: {e}")
        return {'error': str(e)}


def reset_user_reminder_flags(user_id: int, is_trial: bool = False) -> tuple:
    """
    重置用户提醒标志（用于测试或在续费后调用）
    
    Args:
        user_id: 用户ID
        is_trial: 是否为试用期用户
        
    Returns:
        (success, message)
    """
    try:
        with get_db_context() as db:
            user = db.query(User).filter(User.id == user_id).first()
            if not user:
                return False, "用户不存在"
            
            if is_trial:
                user.trial_reminder_3day_sent = False
                user.trial_reminder_1day_sent = False
                user.trial_reminder_recall_sent = False
            else:
                user.reminder_3day_sent = False
                user.reminder_1day_sent = False
                user.reminder_recall_sent = False
                user.last_reminder_sent = None
            
            return True, "提醒标志已重置"
    except Exception as e:
        logger.error(f"重置提醒标志失败: {e}")
        return False, str(e)


def test_reminder_email(user_id: int, reminder_type: str = 'sub_3day') -> tuple:
    """
    测试发送提醒邮件给指定用户（管理员功能）
    
    Args:
        user_id: 用户ID
        reminder_type: 提醒类型 (sub_3day, sub_1day, sub_recall, trial_3day, trial_1day, trial_recall)
        
    Returns:
        (success, message)
    """
    valid_types = ['sub_3day', 'sub_1day', 'sub_recall', 'trial_3day', 'trial_1day', 'trial_recall']
    if reminder_type not in valid_types:
        return False, f"无效的提醒类型，可选: {valid_types}"
    
    try:
        with get_db_context() as db:
            user = db.query(User).filter(User.id == user_id).first()
            if not user:
                return False, "用户不存在"
        
        success = _send_expiry_reminder(user, reminder_type)
        if success:
            return True, f"测试邮件已发送给 {user.email}"
        else:
            return False, "邮件发送失败，请检查邮件服务配置"
    except Exception as e:
        logger.error(f"发送测试邮件失败: {e}")
        return False, str(e)
